### ISSUE TITLE
容器拉不起来，提示有问题。

### ISSUE THREAD

**Issue by rebron1900** [ZhaoUncle/memos-proxy#1]
![image](https://user-images.githubusercontent.com/7929884/186800899-6ed6bc25-1a16-4af4-bb81-9c878db7982d.png)

**Comment by ZhaoUncle** [comment]
是的，看报错你就是没改配置文件映射进去。默认我就是设置的无法启动，因为配置文件我就没放进去

**Comment by ZhaoUncle** [comment]
你提醒我了，我改一下镜像，重新push一个

**Comment by rebron1900** [comment]
我手动创建了配置文件，成功拉起来了
但是微信后台服务器设置一直提醒token验证失败。
我看了代码文件后尝试在在config.ini里加入wechat_token后设置的值和服务器配置那里一样，还是不行，请问要怎么处理呢？

**Comment by rebron1900** [comment]
是我的问题，我服务器地址没加上/wechat

**Comment by ZhaoUncle** [comment]
是，有事没看看文档，里面说的很清楚。

**Comment by rebron1900** [comment]
成功了，感谢。
另外图片可以使用bber的方式，通过后续的命令来修改上一条memos
比如：
1. 先把图片发出去
2. 后续通过/a、/i 之类的命令给图片添加文字（后台其实就是更新上一条memos数据。

**Comment by rebron1900** [comment]
可以参考这个项目：
https://github.com/lmm214/bber/blob/main/bber/index.js

**Comment by ZhaoUncle** [comment]
可以考虑， 因为我用不到，暂时没考虑这么做，本身memos的api文档也不全。不是很想折腾。
